#!/bin/bash

if [ "$#" -lt 2 ]; then
  echo "Command arg format: ['master' OR odk PR number] [tag OR feature path]"
  echo "for example:"
  echo "    ./run master @Basic"
  echo "    ./run release @Integration"
  echo "    ./run 1059 feature/lookup_table_sync.feature"
  echo "    ./run version feature/lookup_table_sync.feature 2.29"
  exit
fi

BUILD=$1
TAG=$2
VERSION=$3

# Find next version number, IE 2.33 -> 2.34
IFS='.' read -a VERSION_ARRAY <<< "$3"
MAJOR_VERSION="${VERSION_ARRAY[0]}"
MINOR_VERSION="${VERSION_ARRAY[1]}"
NEW_MINOR_VERSION="$((MINOR_VERSION+1))"
NEW_VERSION_TAG="${MAJOR_VERSION}.${NEW_MINOR_VERSION}"

rm "*.png"
rm -rf "reports"
rm "commcare.apk"

# make sure we aren't in airplane mode
IN_AIRPLANE=$(adb shell settings get global airplane_mode_on | tr -d '\r')
if [[ "$IN_AIRPLANE" -eq "1" ]]; then
  adb shell am start -a android.settings.AIRPLANE_MODE_SETTINGS && sleep 0.5
  adb shell input keyevent 19 && sleep 0.3 && adb shell input keyevent 23
  adb shell input keyevent 4
fi

# download/build apk
if [ "$BUILD" == "master" ]; then
  echo "downloading latest master apk from jenkins"
  wget "https://jenkins.dimagi.com/job/commcare-android/lastSuccessfulBuild/artifact/commcare-android/app/build/outputs/apk/app-commcare-release.apk" -O commcare.apk
  bundler exec calabash-android resign commcare.apk
elif [ "$BUILD" == "version" ]; then
  echo "downloading latest master apk from jenkins"
  wget "https://jenkins.dimagi.com/job/commcare-android-$VERSION/lastSuccessfulBuild/artifact/commcare-android/app/build/outputs/apk/app-commcare-release.apk" -O commcare.apk
  bundler exec calabash-android resign commcare.apk
elif [ "$BUILD" == "release" ]; then
  echo "downloading latest release apk from jenkins"
  URL=$(python3 scripts/get_latest_release_url.py)
  wget $URL -O commcare.apk
  bundler exec calabash-android resign commcare.apk
else
  echo "building from pull request"
  ./scripts/build_pr_apk.py $BUILD
fi

# unlock phone
adb shell input keyevent 82

# run tests
if [[ $TAG = \@* ]] ; then
  FEATURE="--tags $TAG --tags ~@${NEW_VERSION_TAG}"
else
  FEATURE=$TAG
fi
bundler exec calabash-android run commcare.apk $FEATURE --format junit --out reports
