#!/bin/bash

if [ "$#" -ne 2 ]; then
  echo "Command arg format: ['master' OR odk PR number] [tag OR feature path]"
  echo "for example:"
  echo "    ./run master @Integration"
  echo "    ./run 1059 feature/lookup_table_sync.feature"
  exit
fi

BUILD=$1
TAG=$2

rm "*.png"
rm -rf "reports"
rm "commcare.apk"

# download/build apk
if [ "$BUILD" == "master" ]; then
  echo "downloading latest master apk from jenkins"
  wget "https://jenkins.dimagi.com/job/commcare-android/lastSuccessfulBuild/artifact/commcare-android/build/outputs/apk/commcare-android-commcare-release.apk" -O commcare.apk
  calabash-android resign commcare.apk
elif [ "$BUILD" == "release" ]; then
  echo "downloading latest release apk from jenkins"
  URL=$(./scripts/get_latest_release_url.py)
  wget $URL -O commcare.apk
  calabash-android resign commcare.apk
else
  echo "building from pull request"
  ./scripts/build_pr_apk.py $BUILD
fi

# unlock phone
# adb shell input keyevent 82

# run tests
if [[ $TAG = \@* ]] ; then
  FEATURE="--tags $TAG"
else
  FEATURE=$TAG
fi
calabash-android run commcare.apk $FEATURE --format junit --out reports
