// Should send email/slack notification
def notify = true
// Number of times to retry a failed test
def retries = 1
// Pool of devices on AWS to run on
def pool = 'asus_5_1'

// Job to copy the tested APK from
def cc_android_job = env.CUSTOM_JOB_TARGET ? "${CUSTOM_JOB_TARGET}" : 'commcare-android'

def custom_tag =  env.CUSTOM_TAG_TO_RUN ? "${CUSTOM_TAG_TO_RUN}" : ''

def pipeline_runner_branch_target =  env.target_ui_test_branch ? "${target_ui_test_branch}" : 'master'

def buildPassing = true

def failureList = []
def failureList2 = []
def failureList3 = []
def failureListFinal = []

node {
    stage('test') {
        
        // All of the tags run on AWS. We specify these individually so that we can iterate over each
        // tag and retry them granularly when they fail.

        def ui_tests_list = ['@FormEntry', '@Fixtures', '@MenuTests', '@Login',
                       '@FormSettings', '@CaseSharing', '@Languages',
                       '@CaseListSearch', '@CaseListSort', '@Settings', '@FormFiltering', '@Tiles',
                       '@SessionExpiration', '@Dialogs', '@InstallList', '@DemoUserOnline', '@DemoUserOffline',
                       '@LookupTableOptionSorting', '@ManualQuarantine', '@LogSubmission']

        def integration_tests_list = ['@DeletedUser', '@SyncRecovery', '@SubmissionErrorResponse', '@AsyncRestore',
                                '@LookupTableSync','@AppUpdate', '@FormAttachmentUpload', '@CaseClaim', '@InstallList']

        def tagArray
        if (custom_tag != '') {
             if (custom_tag.indexOf(',') > 0) {
               // Parse as a list if contains commas
               tagArray = Eval.me(custom_tag)
             } else {
               tagArray =  [custom_tag]
             }
        } else if (env.integration_job == 'true') {
             tagArray = integration_tests_list
        } else {
             tagArray = ui_tests_list
        }

        try {
            echo 'Running tests...'

            // Run the commcare-odk-tests job for each device pool and each tag, retrying up to three
            // times on failures
            for (tag in tagArray) {
                def stageString = "${tag} on ${pool}"
                count = 0
                try {
                    retry(retries) {
                        stage ("${stageString} try 1") {
                            count = count + 1
                            echo "Testing ${stageString} try number 1 tag ${tag}"
                            def testRun = build job: 'pipeline-runner', parameters: [
                                [$class: 'StringParameterValue', name: 'pool', value: pool],
                                [$class: 'StringParameterValue', name: 'stageString', value: stageString],
                                [$class: 'StringParameterValue', name: 'tag', value: tag],
                                [$class: 'StringParameterValue', name: 'target_ui_test_branch', value: pipeline_runner_branch_target],
                                [$class: 'StringParameterValue', name: 'cc_android_job', value: cc_android_job]
                            ]
                            echo "Step ${stageString} set to SUCCESS"
                        }
                    }
                } catch (exc) {
                    echo "Step ${stageString} set to FAILURE"
                    failureList.add(tag)
                }
            }

            def failingListString1 = failureList.join(",")
            echo "Failed first round with failing tags ${failingListString1}"
            pool = 'asus_4_4'

            for (tag in failureList) {
                def stageString = "${tag} on ${pool}"
                count = 0
                try {
                    retry(retries) {
                        stage ("${stageString} try 2") {
                            count = count + 1
                            echo "Testing ${stageString} try number 2 tag ${tag}"
                            def testRun = build job: 'pipeline-runner', parameters: [
                                [$class: 'StringParameterValue', name: 'pool', value: pool],
                                [$class: 'StringParameterValue', name: 'stageString', value: stageString],
                                [$class: 'StringParameterValue', name: 'tag', value: tag],
                                [$class: 'StringParameterValue', name: 'target_ui_test_branch', value: pipeline_runner_branch_target],
                                [$class: 'StringParameterValue', name: 'cc_android_job', value: cc_android_job]
                            ]
                            echo "Step ${stageString} set to SUCCESS"
                        }
                    }
                } catch (exc) {
                    echo "Step ${stageString} set to FAILURE"
                    failureList2.add(tag)
                }
            }

            def failingListString2 = failureList2.join(",")
            echo "Failed second round with failing tags ${failingListString2}"
            pool = 'asus_5_0'

            for (tag in failureList2) {
                def stageString = "${tag} on ${pool}"
                count = 0
                try {
                    retry(retries) {
                        stage ("${stageString} try 3") {
                            count = count + 1
                            echo "Testing ${stageString} try number 3 tag ${tag}"
                            def testRun = build job: 'pipeline-runner', parameters: [
                                [$class: 'StringParameterValue', name: 'pool', value: pool],
                                [$class: 'StringParameterValue', name: 'stageString', value: stageString],
                                [$class: 'StringParameterValue', name: 'tag', value: tag],
                                [$class: 'StringParameterValue', name: 'target_ui_test_branch', value: pipeline_runner_branch_target],
                                [$class: 'StringParameterValue', name: 'cc_android_job', value: cc_android_job]
                            ]
                            echo "Step ${stageString} set to SUCCESS"
                        }
                    }
                } catch (exc) {
                    echo "Step ${stageString} set to FAILURE"
                    buildPassing = false
                    failureList3.add(tag)
                }
            }

            pool = 'asus_6_0'

            for (tag in failureList3) {
                def stageString = "${tag} on ${pool}"
                count = 0
                try {
                    retry(retries) {
                        stage ("${stageString} try 4") {
                            count = count + 1
                            echo "Testing ${stageString} try number 4 tag ${tag}"
                            def testRun = build job: 'pipeline-runner', parameters: [
                                [$class: 'StringParameterValue', name: 'pool', value: pool],
                                [$class: 'StringParameterValue', name: 'stageString', value: stageString],
                                [$class: 'StringParameterValue', name: 'tag', value: tag],
                                [$class: 'StringParameterValue', name: 'target_ui_test_branch', value: pipeline_runner_branch_target],
                                [$class: 'StringParameterValue', name: 'cc_android_job', value: cc_android_job]
                            ]
                            echo "Step ${stageString} set to SUCCESS"
                        }
                    }
                } catch (exc) {
                    echo "Step ${stageString} set to FAILURE"
                    buildPassing = false
                    failureListFinal.add(tag)
                }
            }
        }
        finally {
            def failingListStringFinal = failureListFinal.join(",")
            if (buildPassing) {
                echo "Passed"
                currentBuild.result = 'SUCCESS'
            } else {
                echo "Failed with failing tags ${failingListStringFinal}"
                currentBuild.result = 'FAILURE'
            }
            if (notify) {
                def test_label = env.integration_job == 'true' ? "Integration" : "UI"
                if (buildPassing) {
                    slackSend color: 'good', message: "${cc_android_job} ${test_label} tests passed, :tight:"
                } else {
                    slackSend color: 'bad', message: "${cc_android_job} ${test_label} tests failed, :nottight:. Failing tests ${failingListStringFinal}"
                    mail (to: 'mobiledev@dimagi.com',
                        subject: "Amazon device farm tests failed.",
                        body: "${cc_android_job} ${test_label} tests failed, weak! Failing tests ${failingListStringFinal}");
                }
            }
        }
    }
}
