stage('build') {
    build job: 'commcare-odk-build-tests'
}

def notify = false

stage('test') {

    def tagArray = ['@Fixtures', '@FormSettings', '@Login', '@Setup', '@CaseSharing', '@FormEntry', '@Languages',
                    '@CaseListSearch', '@CaseListSort', '@Settings', '@FormFiltering', '@SessionExpiration',
                    '@Dialogs', '@MenuTests']
    def poolArray = ['htc']

    try {
        echo 'Running tests...'
        currentBuild.result = 'SUCCESS'
        for (pool in poolArray) {
            for (tag in tagArray) {
                def stageString = "Testing ${tag} on ${pool}"
                try {
                    stage(stageString) {
                        count = 1
                        retry(3) {
                            echo "Testing ${stageString} try number ${count}"
                            build job: 'commcare-odk-tests',
                                        parameters: [
                                            [$class: 'StringParameterValue', name: "TAG_NAME", value: "${tag}"],
                                            [$class: 'StringParameterValue', name: "AWSDEVICEFARM_DEVICE_POOL", value: "${pool}"]]
                        }
                    }
                } catch(error) {
                    echo "Failed testing ${stageString}"
                    currentBuild.result = 'FAILURE'
                }
            }
        }
    } finally {
        if (notify) {
            if (currentBuild.result == 'SUCCESS') {
                slackSend color: 'good', message: 'Amazon device farm tests passed, :tight:'
            } else {
                slackSend color: 'bad', message: 'Amazon device farm tests failed, :nottight:'
                mail (to: 'mobiledev@dimagi.com',
                    subject: "Amazon device farm tests failed.",
                    body: "Amazon device farm tests failed.");
            }
        }
    }
}